Repository CSC207-2023Y-UofT/course-project-held-together-by-duct-tape, pull requests merged in 2023-08, with the labels that each got.

#69 Create student documentation tests and readme
  src/main/java/Main.java
  src/main/java/frameworksdrivers/DatabaseDriver.java
  src/main/java/frameworksdrivers/Gateways/StudentDbGateway.java
  src/main/java/interfaceadapters/CreateCourseInterfaceAdapters/CreateCourseController.java
  src/main/java/interfaceadapters/CreateCourseInterfaceAdapters/CreateCoursePresenter.java
  src/main/java/interfaceadapters/CreateStudentInterfaceAdapters/CreateStudentController.java
  src/main/java/interfaceadapters/CreateStudentInterfaceAdapters/CreateStudentPresenter.java
  src/main/java/userinterface/CreateStudentUserInterface/CreateStudentScreen.java
  src/main/java/userinterface/InstuctorCreateCourseUserInterface/CreateCourseScreen.java
  src/test/java/entities/StudentTest.java
  src/test/java/frameworksdriversmock/StudentDbGatewayMock.java
  src/test/java/interfaceadapters/CreateStudentInterfaceAdapters/CreateStudentControllerTest.java
  src/test/java/interfaceadapters/CreateStudentInterfaceAdapters/CreateStudentPresenterTest.java
  src/test/java/usecases/CreateStudentUsecase/CreateStudentInteractorTest.java
Labels: bug, documentation, enhancement

#70 Refactoring Main to remove presenter dependency
  src/main/java/Main.java
  src/main/java/frameworksdrivers/DatabaseDriver.java
  src/main/java/frameworksdrivers/Gateways/CourseDbGateway.java
  src/main/java/frameworksdrivers/Gateways/StudentDbGateway.java
  src/main/java/interfaceadapters/LoginStudentInterfaceAdapters/LoginStudentController.java
  src/main/java/userinterface/LoginStudentUserInterface/LoginStudentScreen.java
  src/test/java/interfaceadapters/LoginStudentInterfaceAdapters/LoginStudentControllerTest.java
  src/test/java/interfaceadapters/LoginStudentInterfaceAdapters/LoginStudentPresenterTest.java
  src/test/java/usecases/LoginStudentUseCase/LoginStudentInteractorTest.java
Labels: enhancement

#72 Feature3 course enrollment
  src/main/java/Main.java
  src/main/java/frameworksdrivers/Gateways/CourseDbGateway.java
  src/main/java/interfaceadapters/CourseEnrollmentInterfaceAdapters/EnrolmentController.java
  src/main/java/interfaceadapters/CourseEnrollmentInterfaceAdapters/EnrolmentPresenter.java
  src/main/java/usecases/CourseEnrollmentUseCase/CheckPrerequisitesInteractor.java
  src/main/java/usecases/CourseEnrollmentUseCase/CourseEnrolmentInteractor.java
  src/main/java/usecases/CourseEnrollmentUseCase/EnrolmentCourseDataAccess.java
  src/main/java/usecases/CourseEnrollmentUseCase/EnrolmentDbRequestModel.java
  src/main/java/usecases/CourseEnrollmentUseCase/EnrolmentInputBoundary.java
  src/main/java/usecases/CourseEnrollmentUseCase/EnrolmentOutputBoundary.java
  src/main/java/usecases/CourseEnrollmentUseCase/EnrolmentRequestModel.java
  src/main/java/usecases/CourseEnrollmentUseCase/EnrolmentResponseModel.java
  src/main/java/usecases/CourseEnrollmentUseCase/EnrolmentSessionDataAccess.java
  src/main/java/userinterface/CourseEnrollmentUserInterface/CourseEnrollmentScreen.java
  src/test/java/interfaceadapters/CourseEnrollmentInterfaceAdapters/EnrolmentControllerTest.java
  src/test/java/interfaceadapters/CourseEnrollmentInterfaceAdapters/EnrolmentPresenterTest.java
  src/test/java/usecases/CourseEnrollmentUseCase/CheckPrerequisitesInteractorTest.java
  src/test/java/usecases/CourseEnrollmentUseCase/CourseEnrolmentInteractorTest.java
  src/test/java/usecases/RunCourseUseCase/RunCourseInteractorTest.java
Labels: enhancement

#73 Feature6 instructor create course
  src/main/java/Main.java
  src/main/java/entities/Course.java
  src/main/java/frameworksdrivers/Gateways/CourseDbGateway.java
  src/main/java/frameworksdrivers/Gateways/CourseGateway.java
  src/main/java/interfaceadapters/CreateCourseInterfaceAdapters/CreateCourseController.java
  src/main/java/interfaceadapters/CreateCourseInterfaceAdapters/CreateCoursePresenter.java
  src/main/java/interfaceadapters/CreateCourseInterfaceAdapters/FailedtoCreate.java
  src/main/java/interfaceadapters/CreateCourseInterfaceAdapters/SuccessCreate.java
  src/main/java/usecases/InstructorCreateCourseUseCase/CourseDataAccess.java
  src/main/java/usecases/InstructorCreateCourseUseCase/CourseDbRequestModel.java
  src/main/java/usecases/InstructorCreateCourseUseCase/CreateCourseInputBoundary.java
  src/main/java/usecases/InstructorCreateCourseUseCase/CreateCourseInteractor.java
  src/main/java/usecases/InstructorCreateCourseUseCase/CreateCourseOutputBoundary.java
  src/main/java/usecases/InstructorCreateCourseUseCase/CreateCourseRequestModel.java
  src/main/java/usecases/InstructorCreateCourseUseCase/CreateCourseResponseModel.java
  src/main/java/userinterface/CreateStudentUserInterface/CreateStudentScreen.java
  src/main/java/userinterface/InstuctorCreateCourseUserInterface/CreateCourseScreen.java
  src/main/java/userinterface/StudentModeScreen.java
  src/main/java/userinterface/UserModeScreen.java
  src/test/java/frameworksdriversmock/CourseDbGatewayMock.java
  src/test/java/interfaceadapters/CreateCourseInterfaceAdapters/CreateCourseControllerTest.java
  src/test/java/interfaceadapters/CreateCourseInterfaceAdapters/CreateCoursePresenterTest.java
  src/test/java/usecases/CreateStudentUsecase/CreateStudentInteractorTest.java
  src/test/java/usecases/InstructorCreateCourseUseCase/CreateCourseInteractorTest.java
Labels: enhancement

#77 Feature5 course evaluator
  src/test/java/frameworksdriversmock/CourseDbGatewayMock.java
  src/test/java/frameworksdriversmock/SessionDbGatewayMock.java
  src/test/java/usecases/CourseEvaluatorUseCase/CheckAnswersTest.java
  src/test/java/usecases/CourseEvaluatorUseCase/EvaluatorInteractorTest.java
Labels: enhancement

#78 read me edits
  README.md
Labels: documentation

#75 Refactoring the session database to contain password
  resources/courses.ibd
  resources/sessioncourse.ibd
  resources/sessionstudent.ibd
  resources/students.ibd
  src/main/java/Main.java
  src/main/java/frameworksdrivers/DatabaseDriver.java
  src/main/java/frameworksdrivers/Gateways/SessionDbGateway.java
  src/main/java/frameworksdrivers/Gateways/StudentDbGateway.java
  src/main/java/interfaceadapters/LoginStudentInterfaceAdapters/LoginStudentPresenter.java
  src/main/java/usecases/CourseEvaluatorUseCase/EvaluatorDbRequestModel.java
  src/main/java/usecases/CourseEvaluatorUseCase/EvaluatorInteractor.java
  src/main/java/usecases/CourseEvaluatorUseCase/EvaluatorSessionDataAccess.java
  src/main/java/usecases/LoginStudentUseCase/LoginStudentDbRequestModel.java
  src/main/java/userinterface/RunCourseUserInterface/RunCourseScreen.java
  src/test/java/frameworksdriversmock/SessionDbGatewayMock.java
Labels: enhancement
